# Site settings
title: Russel Dave Cruz
name: Russel Dave Cruz

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Facebook
   url: https://facebook.com/russelcruz01

#Any buzzword skills you want to include
skills:
 - Networking
 - Cisco
 - Mikrotik
 - Programming
 - Web Development
 - Laravel
 - Jquery
 - Bootstrap
 - Vuejs
 - Database Management
 - Raspberry
 - Python

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: IT Technician
   start: 2018
   end: Ongoing
   employer: Grand Innovasia Concept Corporation
   description: The company’s primary purpose is “to engage in recreation, leisure resort, games and amusement center, particularly but not limited to online/interactive gaming, computer games and other related recreational activities”. 

#Education is required
education:
 - level: Bachelor of Science
   date: 2017
   subject: Information Technology
   school: Polytechnic University of the Philippines


#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
# - robhind/robhinds.github.io

#Stackoverflow flair is optional
stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: |
  I am an IT with experience working in Networking and some Technical Assistance.  I have primarily worked on the GICC  across a broad range of services to our customers like: internal ISP, Computer Technician, CCTV Technician, Printer Technician, and some Technological Support.<br/></br>
  I enjoy building interesting stuffs that pinned my interest, with a good understanding about software and hardware technology, I enjoy to build something just to past some free time.  I can somehow develop a software, mainly a website using Laravel decent enough to be usable with a readable coding. <br/></br>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>Networking</strong>:My work is based on providing internet access to a certain user/office, therefore I am familiar with Cisco, Mikrotik and some networking devices<br/><br/>   
  <strong>Laravel</strong>: I have used Laravel framework haphazardly before. Through this experience I am confident to say that I improved alot with my debugging skills and understanding on this framework as a whole.<br/><br/>
  <strong>Raspberry</strong>: Since this is just a new hobby to leisure some free time, I can only say that I can somehow or another use Raspbian just like any Desktop. Using this, I make something which pinned my interest just like a child trying the things they found out.</br></br>
  Since I am knowledgable about technology, I help the church I belong to, which is providing support like using my knowledge to ease the problem my churchmate encounters on technology.<br/></br>